services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_production
    restart: always
    stop_grace_period: 30s
    env_file:
      - .env
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-storage:/qdrant/storage
      - qdrant-snapshots:/qdrant/snapshots
      - ./config/production.yaml:/qdrant/config/production.yaml

volumes:
  qdrant-storage:
  qdrant-snapshots: