services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_production
    restart: always
    env_file:
      - .env
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage
      - ./qdrant_snapshots:/qdrant/snapshots
      - ./config/production.yaml:/qdrant/config/production.yaml