log_level: INFO

storage:
  storage_path: /qdrant/storage
  snapshots_path: /qdrant/snapshots
  on_disk_payload: true
  wal:
    wal_capacity_mb: 128
  performance:
    max_search_threads: 0
    max_optimization_threads: 0
  optimizers:
    flush_interval_sec: 1
    default_segment_number: 0
    memmap_threshold_kb: 200000
    indexing_threshold_kb: 200000
  hnsw_index:
    on_disk: true
    m: 32
    ef_construct: 200

service:
  max_workers: 0
